function FindProxyForURL(url, host) {
  host = (host || "").toLowerCase();
  url = (url || "").toLowerCase();

  function PROXY_CONN() { return "PROXY 192.168.50.135:7897"; }
  function DIRECT_CONN() { return "DIRECT"; }

  if (isPlainHostName(host) ||
      shExpMatch(host, "*.local") ||
      shExpMatch(host, "*.lan")) {
    return DIRECT_CONN();
  }

  if (host === "localhost") return DIRECT_CONN();
  if (dnsDomainIs(host, "youtube.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "www.youtube.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "m.youtube.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "youtu.be")) return PROXY_CONN();
  if (dnsDomainIs(host, "youtube.googleapis.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "youtubei.googleapis.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "youtubeembeddedplayer.googleapis.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "googlevideo.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "ytimg.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "s.ytimg.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "i.ytimg.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "ggpht.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "googleusercontent.com")) return PROXY_CONN();
  if (url.indexOf("youtube") !== -1 || host.indexOf("youtube") !== -1) return PROXY_CONN();
  if (url.indexOf("googlevideo") !== -1 || host.indexOf("googlevideo") !== -1) return PROXY_CONN();
  if (url.indexOf("ytimg") !== -1 || host.indexOf("ytimg") !== -1) return PROXY_CONN();
  if (url.indexOf("ggpht") !== -1 || host.indexOf("ggpht") !== -1) return PROXY_CONN();
  if (dnsDomainIs(host, "discord.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "discord.gg")) return PROXY_CONN();
  if (dnsDomainIs(host, "discordapp.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "discordapp.net")) return PROXY_CONN();
  if (dnsDomainIs(host, "discordcdn.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "cdn.discordapp.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "media.discordapp.net")) return PROXY_CONN();
  if (dnsDomainIs(host, "images-ext-1.discordapp.net")) return PROXY_CONN();
  if (dnsDomainIs(host, "images-ext-2.discordapp.net")) return PROXY_CONN();
  if (dnsDomainIs(host, "status.discord.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "discord.media")) return PROXY_CONN();
  if (dnsDomainIs(host, "gateway.discord.gg")) return PROXY_CONN();
  if (dnsDomainIs(host, "voice.discord.gg")) return PROXY_CONN();
  if (dnsDomainIs(host, "clientconfig.discord.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "discord-attachments-uploads-prd.storage.googleapis.com")) return PROXY_CONN();
  if (url.indexOf("rpc") !== -1 || host.indexOf("rpc") !== -1) return PROXY_CONN();
  if (url.indexOf("discord-media") !== -1 || host.indexOf("discord-media") !== -1) return PROXY_CONN();
  if (url.indexOf("discord-gateway") !== -1 || host.indexOf("discord-gateway") !== -1) return PROXY_CONN();
  if (url.indexOf("discord") !== -1 || host.indexOf("discord") !== -1) return PROXY_CONN();
  if (host === "reddit.com") return PROXY_CONN();
  if (host === "www.reddit.com") return PROXY_CONN();
  if (host === "oauth.reddit.com") return PROXY_CONN();
  if (host === "gateway.reddit.com") return PROXY_CONN();
  if (host === "events.reddit.com") return PROXY_CONN();
  if (dnsDomainIs(host, "redd.it")) return PROXY_CONN();
  if (dnsDomainIs(host, "redditstatic.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "redditmedia.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "reddituploads.com")) return PROXY_CONN();
  if (host === "i.redd.it") return PROXY_CONN();
  if (host === "preview.redd.it") return PROXY_CONN();
  if (host === "v.redd.it") return PROXY_CONN();
  if (dnsDomainIs(host, "openai.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "chatgpt.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "ai.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "auth0.openai.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "chat.openai.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "cdn.openai.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "oaiusercontent.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "openaicom.imgix.net")) return PROXY_CONN();
  if (dnsDomainIs(host, "openaicom-api.akamaized.net")) return PROXY_CONN();
  if (dnsDomainIs(host, "threads.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "threads.net")) return PROXY_CONN();
  if (url.indexOf("threads") !== -1 || host.indexOf("threads") !== -1) return PROXY_CONN();
  if (dnsDomainIs(host, "instagram.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "i.instagram.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "api.instagram.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "graph.instagram.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "b-graph.instagram.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "cdninstagram.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "static.cdninstagram.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "scontent.cdninstagram.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "igcdn.net")) return PROXY_CONN();
  if (dnsDomainIs(host, "instagram.c10r.facebook.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "facebook.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "facebook.net")) return PROXY_CONN();
  if (dnsDomainIs(host, "fb.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "fbcdn.net")) return PROXY_CONN();
  if (dnsDomainIs(host, "xx.fbcdn.net")) return PROXY_CONN();
  if (dnsDomainIs(host, "tfbnw.net")) return PROXY_CONN();
  if (dnsDomainIs(host, "connect.facebook.net")) return PROXY_CONN();
  if (dnsDomainIs(host, "edge-chat.facebook.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "edge-mqtt.facebook.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "mqtt-mini.facebook.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "star.c10r.facebook.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "star-mini.c10r.facebook.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "graph.facebook.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "video.xx.fbcdn.net")) return PROXY_CONN();
  if (dnsDomainIs(host, "scontent.xx.fbcdn.net")) return PROXY_CONN();
  if (dnsDomainIs(host, "static.xx.fbcdn.net")) return PROXY_CONN();
  if (dnsDomainIs(host, "whatsapp.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "whatsapp.net")) return PROXY_CONN();
  if (url.indexOf("instagram") !== -1 || host.indexOf("instagram") !== -1) return PROXY_CONN();
  if (url.indexOf("fbcdn") !== -1 || host.indexOf("fbcdn") !== -1) return PROXY_CONN();
  if (url.indexOf("facebook") !== -1 || host.indexOf("facebook") !== -1) return PROXY_CONN();
  if (url.indexOf("scontent") !== -1 || host.indexOf("scontent") !== -1) return PROXY_CONN();
  if (url.indexOf("metaverse") !== -1 || host.indexOf("metaverse") !== -1) return PROXY_CONN();
  if (dnsDomainIs(host, "meta.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "graph.meta.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "horizon.meta.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "horizon.oculus.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "oculus.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "oculuscdn.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "oculusvr.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "graph.oculus.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "secure.oculus.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "edge.oculus.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "mqtt.meta.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "mqtt-mini.meta.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "edge-mqtt.meta.com")) return PROXY_CONN();
  if (url.indexOf("oculus") !== -1 || host.indexOf("oculus") !== -1) return PROXY_CONN();
  if (url.indexOf("quest") !== -1 || host.indexOf("quest") !== -1) return PROXY_CONN();
  if (url.indexOf("horizon") !== -1 || host.indexOf("horizon") !== -1) return PROXY_CONN();
  if (dnsDomainIs(host, "notion.so")) return PROXY_CONN();
  if (dnsDomainIs(host, "notion.site")) return PROXY_CONN();
  if (dnsDomainIs(host, "notion-static.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "proton.me")) return PROXY_CONN();
  if (dnsDomainIs(host, "protonmail.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "protonvpn.com")) return PROXY_CONN();
  if (url.indexOf("proton") !== -1 || host.indexOf("proton") !== -1) return PROXY_CONN();
  if (dnsDomainIs(host, "garlandtools.org")) return PROXY_CONN();
  if (dnsDomainIs(host, "universalis.app")) return PROXY_CONN();
  if (dnsDomainIs(host, "xivgear.app")) return PROXY_CONN();
  if (dnsDomainIs(host, "raidplan.io")) return PROXY_CONN();
  if (dnsDomainIs(host, "finalfantasyxiv.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "ffxiv.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "square-enix.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "sqexcdn.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "ffxivteamcraft.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "fflogs.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "xivanalysis.com")) return PROXY_CONN();
  if (url.indexOf("lifehacker") !== -1 || host.indexOf("lifehacker") !== -1) return PROXY_CONN();
  if (dnsDomainIs(host, "desec.io")) return PROXY_CONN();
  if (dnsDomainIs(host, "patreon.com")) return PROXY_CONN();
  if (url.indexOf("patreon") !== -1 || host.indexOf("patreon") !== -1) return PROXY_CONN();
  if (dnsDomainIs(host, "canva.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "canva.dev")) return PROXY_CONN();
  if (dnsDomainIs(host, "canvausercontent.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "cdn.canva.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "static.canva.com")) return PROXY_CONN();
  if (url.indexOf("hentaihaven") !== -1 || host.indexOf("hentaihaven") !== -1) return PROXY_CONN();
  if (url.indexOf("hentai") !== -1 || host.indexOf("hentai") !== -1) return PROXY_CONN();
  if (url.indexOf("pornhub") !== -1 || host.indexOf("pornhub") !== -1) return PROXY_CONN();
  if (url.indexOf("phncdn") !== -1 || host.indexOf("phncdn") !== -1) return PROXY_CONN();
  if (url.indexOf("pornolab") !== -1 || host.indexOf("pornolab") !== -1) return PROXY_CONN();
  if (url.indexOf("eporner") !== -1 || host.indexOf("eporner") !== -1) return PROXY_CONN();
  if (url.indexOf("xvideos") !== -1 || host.indexOf("xvideos") !== -1) return PROXY_CONN();
  if (url.indexOf("xnxx") !== -1 || host.indexOf("xnxx") !== -1) return PROXY_CONN();
  if (url.indexOf("youporn") !== -1 || host.indexOf("youporn") !== -1) return PROXY_CONN();
  if (url.indexOf("redtube") !== -1 || host.indexOf("redtube") !== -1) return PROXY_CONN();
  if (dnsDomainIs(host, "hanime.tv")) return PROXY_CONN();
  if (dnsDomainIs(host, "hanime-cdn.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "highwinds-cdn.com")) return PROXY_CONN();
  if (url.indexOf("hydaelyn") !== -1 || host.indexOf("hydaelyn") !== -1) return PROXY_CONN();
  if (host === "omni-player.hanime.tv") return PROXY_CONN();
  if (dnsDomainIs(host, "hhcdn.net")) return PROXY_CONN();
  if (dnsDomainIs(host, "hentaicdn.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "hanime1.me")) return PROXY_CONN();
  if (dnsDomainIs(host, "dirtyship.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "ds-cdn.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "ds1cdn.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "cloudflarestream.com")) return PROXY_CONN();
  if (url.indexOf("rutracker") !== -1 || host.indexOf("rutracker") !== -1) return PROXY_CONN();
  if (url.indexOf("rutor") !== -1 || host.indexOf("rutor") !== -1) return PROXY_CONN();
  if (url.indexOf("tfile") !== -1 || host.indexOf("tfile") !== -1) return PROXY_CONN();
  if (url.indexOf("nnmclub") !== -1 || host.indexOf("nnmclub") !== -1) return PROXY_CONN();
  if (url.indexOf("torrent") !== -1 || host.indexOf("torrent") !== -1) return PROXY_CONN();
  if (url.indexOf("1337x") !== -1 || host.indexOf("1337x") !== -1) return PROXY_CONN();
  if (url.indexOf("torlock") !== -1 || host.indexOf("torlock") !== -1) return PROXY_CONN();
  if (url.indexOf("rarbg") !== -1 || host.indexOf("rarbg") !== -1) return PROXY_CONN();
  if (url.indexOf("torrentgalaxy") !== -1 || host.indexOf("torrentgalaxy") !== -1) return PROXY_CONN();
  if (url.indexOf("limetorrents") !== -1 || host.indexOf("limetorrents") !== -1) return PROXY_CONN();
  if (url.indexOf("piratebay") !== -1 || host.indexOf("piratebay") !== -1) return PROXY_CONN();
  if (url.indexOf("seedpeer") !== -1 || host.indexOf("seedpeer") !== -1) return PROXY_CONN();
  if (url.indexOf("bitsearch") !== -1 || host.indexOf("bitsearch") !== -1) return PROXY_CONN();
  if (url.indexOf("magnetdl") !== -1 || host.indexOf("magnetdl") !== -1) return PROXY_CONN();
  if (url.indexOf("torrends") !== -1 || host.indexOf("torrends") !== -1) return PROXY_CONN();
  if (url.indexOf("glotorrents") !== -1 || host.indexOf("glotorrents") !== -1) return PROXY_CONN();
  if (url.indexOf("ettv") !== -1 || host.indexOf("ettv") !== -1) return PROXY_CONN();
  if (url.indexOf("yts") !== -1 || host.indexOf("yts") !== -1) return PROXY_CONN();
  if (url.indexOf("nyaa") !== -1 || host.indexOf("nyaa") !== -1) return PROXY_CONN();
  if (url.indexOf("animetosho") !== -1 || host.indexOf("animetosho") !== -1) return PROXY_CONN();
  if (dnsDomainIs(host, "servarr.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "radarr.video")) return PROXY_CONN();
  if (dnsDomainIs(host, "api.radarr.video")) return PROXY_CONN();
  if (dnsDomainIs(host, "sonarr.tv")) return PROXY_CONN();
  if (dnsDomainIs(host, "lidarr.audio")) return PROXY_CONN();
  if (dnsDomainIs(host, "api.lidarr.audio")) return PROXY_CONN();
  if (dnsDomainIs(host, "jackett.dev")) return PROXY_CONN();
  if (url.indexOf("jackett") !== -1 || host.indexOf("jackett") !== -1) return PROXY_CONN();
  if (dnsDomainIs(host, "flaresolverr")) return PROXY_CONN();
  if (dnsDomainIs(host, "tmdb.org")) return PROXY_CONN();
  if (dnsDomainIs(host, "themoviedb.org")) return PROXY_CONN();
  if (dnsDomainIs(host, "opensubtitles.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "www.opensubtitles.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "api.opensubtitles.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "opensubtitles.org")) return PROXY_CONN();
  if (dnsDomainIs(host, "opensubtitles.vip")) return PROXY_CONN();
  if (dnsDomainIs(host, "podnapisi.net")) return PROXY_CONN();
  if (dnsDomainIs(host, "www.podnapisi.net")) return PROXY_CONN();
  if (dnsDomainIs(host, "yifysubtitles.ch")) return PROXY_CONN();
  if (dnsDomainIs(host, "yifysubtitles.org")) return PROXY_CONN();
  if (dnsDomainIs(host, "yts.mx")) return PROXY_CONN();
  if (dnsDomainIs(host, "subscene.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "addic7ed.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "musicbrainz.org")) return PROXY_CONN();
  if (dnsDomainIs(host, "metabrainz.org")) return PROXY_CONN();
  if (dnsDomainIs(host, "coverartarchive.org")) return PROXY_CONN();
  if (dnsDomainIs(host, "fanart.tv")) return PROXY_CONN();
  if (dnsDomainIs(host, "theaudiodb.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "last.fm")) return PROXY_CONN();
  if (dnsDomainIs(host, "discogs.com")) return PROXY_CONN();
  if (dnsDomainIs(host, "acoustid.org")) return PROXY_CONN();
  if (dnsDomainIs(host, "acousticbrainz.org")) return PROXY_CONN();
  if (dnsDomainIs(host, "brainz.org")) return PROXY_CONN();
  if (dnsDomainIs(host, "musicbrainzpicard.live")) return PROXY_CONN();
  return DIRECT_CONN();
}