function FindProxyForURL(url, host) {
  host = host.toLowerCase();
  url = url.toLowerCase();

  function PROXY() { return "PROXY 192.168.50.135:7897"; }
  function DIRECT_CONN() { return "DIRECT"; }

  if (dnsDomainIs(host, "youtube.com")) return PROXY();
  if (dnsDomainIs(host, "www.youtube.com")) return PROXY();
  if (dnsDomainIs(host, "m.youtube.com")) return PROXY();
  if (dnsDomainIs(host, "youtu.be")) return PROXY();
  if (dnsDomainIs(host, "youtube.googleapis.com")) return PROXY();
  if (dnsDomainIs(host, "youtubei.googleapis.com")) return PROXY();
  if (dnsDomainIs(host, "youtubeembeddedplayer.googleapis.com")) return PROXY();
  if (dnsDomainIs(host, "googlevideo.com")) return PROXY();
  if (dnsDomainIs(host, "ytimg.com")) return PROXY();
  if (dnsDomainIs(host, "s.ytimg.com")) return PROXY();
  if (dnsDomainIs(host, "i.ytimg.com")) return PROXY();
  if (url.indexOf("youtube") !== -1) return PROXY();
  if (url.indexOf("googlevideo") !== -1) return PROXY();
  if (url.indexOf("ytimg") !== -1) return PROXY();
  if (url.indexOf("ggpht") !== -1) return PROXY();
  if (dnsDomainIs(host, "discord.com")) return PROXY();
  if (dnsDomainIs(host, "discord.gg")) return PROXY();
  if (dnsDomainIs(host, "discordapp.com")) return PROXY();
  if (dnsDomainIs(host, "discordapp.net")) return PROXY();
  if (dnsDomainIs(host, "discordcdn.com")) return PROXY();
  if (dnsDomainIs(host, "cdn.discordapp.com")) return PROXY();
  if (dnsDomainIs(host, "media.discordapp.net")) return PROXY();
  if (dnsDomainIs(host, "images-ext-1.discordapp.net")) return PROXY();
  if (dnsDomainIs(host, "images-ext-2.discordapp.net")) return PROXY();
  if (dnsDomainIs(host, "status.discord.com")) return PROXY();
  if (dnsDomainIs(host, "discord.media")) return PROXY();
  if (dnsDomainIs(host, "gateway.discord.gg")) return PROXY();
  if (dnsDomainIs(host, "voice.discord.gg")) return PROXY();
  if (dnsDomainIs(host, "clientconfig.discord.com")) return PROXY();
  if (dnsDomainIs(host, "discord-attachments-uploads-prd.storage.googleapis.com")) return PROXY();
  if (url.indexOf("rpc") !== -1) return PROXY();
  if (url.indexOf("discord-media") !== -1) return PROXY();
  if (url.indexOf("discord-gateway") !== -1) return PROXY();
  if (url.indexOf("discord") !== -1) return PROXY();
  if (dnsDomainIs(host, "openai.com")) return PROXY();
  if (dnsDomainIs(host, "chatgpt.com")) return PROXY();
  if (dnsDomainIs(host, "ai.com")) return PROXY();
  if (dnsDomainIs(host, "auth0.openai.com")) return PROXY();
  if (dnsDomainIs(host, "chat.openai.com")) return PROXY();
  if (dnsDomainIs(host, "cdn.openai.com")) return PROXY();
  if (dnsDomainIs(host, "oaiusercontent.com")) return PROXY();
  if (dnsDomainIs(host, "openaicom.imgix.net")) return PROXY();
  if (dnsDomainIs(host, "openaicom-api.akamaized.net")) return PROXY();
  if (dnsDomainIs(host, "instagram.com")) return PROXY();
  if (dnsDomainIs(host, "i.instagram.com")) return PROXY();
  if (dnsDomainIs(host, "api.instagram.com")) return PROXY();
  if (dnsDomainIs(host, "graph.instagram.com")) return PROXY();
  if (dnsDomainIs(host, "b-graph.instagram.com")) return PROXY();
  if (dnsDomainIs(host, "cdninstagram.com")) return PROXY();
  if (dnsDomainIs(host, "static.cdninstagram.com")) return PROXY();
  if (dnsDomainIs(host, "scontent.cdninstagram.com")) return PROXY();
  if (dnsDomainIs(host, "igcdn.net")) return PROXY();
  if (dnsDomainIs(host, "facebook.com")) return PROXY();
  if (dnsDomainIs(host, "facebook.net")) return PROXY();
  if (dnsDomainIs(host, "fb.com")) return PROXY();
  if (dnsDomainIs(host, "fbcdn.net")) return PROXY();
  if (dnsDomainIs(host, "xx.fbcdn.net")) return PROXY();
  if (dnsDomainIs(host, "tfbnw.net")) return PROXY();
  if (dnsDomainIs(host, "connect.facebook.net")) return PROXY();
  if (dnsDomainIs(host, "edge-chat.facebook.com")) return PROXY();
  if (dnsDomainIs(host, "edge-mqtt.facebook.com")) return PROXY();
  if (dnsDomainIs(host, "mqtt-mini.facebook.com")) return PROXY();
  if (dnsDomainIs(host, "star.c10r.facebook.com")) return PROXY();
  if (dnsDomainIs(host, "star-mini.c10r.facebook.com")) return PROXY();
  if (dnsDomainIs(host, "graph.facebook.com")) return PROXY();
  if (dnsDomainIs(host, "video.xx.fbcdn.net")) return PROXY();
  if (dnsDomainIs(host, "scontent.xx.fbcdn.net")) return PROXY();
  if (dnsDomainIs(host, "static.xx.fbcdn.net")) return PROXY();
  if (dnsDomainIs(host, "instagram.c10r.facebook.com")) return PROXY();
  if (dnsDomainIs(host, "whatsapp.com")) return PROXY();
  if (dnsDomainIs(host, "whatsapp.net")) return PROXY();
  if (url.indexOf("instagram") !== -1) return PROXY();
  if (url.indexOf("fbcdn") !== -1) return PROXY();
  if (url.indexOf("facebook") !== -1) return PROXY();
  if (url.indexOf("scontent") !== -1) return PROXY();
  if (url.indexOf("metaverse") !== -1) return PROXY();
  if (url.indexOf("lifehacker") !== -1) return PROXY();
  if (dnsDomainIs(host, "notion.so")) return PROXY();
  if (dnsDomainIs(host, "notion.site")) return PROXY();
  if (dnsDomainIs(host, "notion-static.com")) return PROXY();
  if (dnsDomainIs(host, "proton.me")) return PROXY();
  if (dnsDomainIs(host, "protonmail.com")) return PROXY();
  if (dnsDomainIs(host, "protonvpn.com")) return PROXY();
  if (url.indexOf("proton") !== -1) return PROXY();
  if (url.indexOf("hentaihaven") !== -1) return PROXY();
  if (url.indexOf("hentai") !== -1) return PROXY();
  if (url.indexOf("pornhub") !== -1) return PROXY();
  if (url.indexOf("phncdn") !== -1) return PROXY();
  if (url.indexOf("pornolab") !== -1) return PROXY();
  if (url.indexOf("eporner") !== -1) return PROXY();
  if (url.indexOf("xvideos") !== -1) return PROXY();
  if (url.indexOf("xnxx") !== -1) return PROXY();
  if (url.indexOf("youporn") !== -1) return PROXY();
  if (url.indexOf("redtube") !== -1) return PROXY();
  if (dnsDomainIs(host, "hanime.tv")) return PROXY();
  if (dnsDomainIs(host, "hhcdn.net")) return PROXY();
  if (dnsDomainIs(host, "hentaicdn.com")) return PROXY();
  if (dnsDomainIs(host, "hanime1.me")) return PROXY();
  if (dnsDomainIs(host, "dirtyship.com")) return PROXY();
  if (dnsDomainIs(host, "ds-cdn.com")) return PROXY();
  if (dnsDomainIs(host, "ds1cdn.com")) return PROXY();
  if (dnsDomainIs(host, "cloudflarestream.com")) return PROXY();
  if (url.indexOf("rutracker") !== -1) return PROXY();
  if (url.indexOf("tfile") !== -1) return PROXY();
  if (url.indexOf("nnmclub") !== -1) return PROXY();
  if (url.indexOf("torrent") !== -1) return PROXY();
  if (url.indexOf("1337x") !== -1) return PROXY();
  if (url.indexOf("torlock") !== -1) return PROXY();
  if (url.indexOf("rarbg") !== -1) return PROXY();
  if (url.indexOf("torrentgalaxy") !== -1) return PROXY();
  if (url.indexOf("limetorrents") !== -1) return PROXY();
  if (url.indexOf("piratebay") !== -1) return PROXY();
  if (url.indexOf("seedpeer") !== -1) return PROXY();
  if (url.indexOf("bitsearch") !== -1) return PROXY();
  if (url.indexOf("magnetdl") !== -1) return PROXY();
  if (url.indexOf("torrends") !== -1) return PROXY();
  if (url.indexOf("glotorrents") !== -1) return PROXY();
  if (url.indexOf("ettv") !== -1) return PROXY();
  if (url.indexOf("yts") !== -1) return PROXY();
  if (url.indexOf("nyaa") !== -1) return PROXY();
  if (url.indexOf("animetosho") !== -1) return PROXY();
  if (dnsDomainIs(host, "radarr.video")) return PROXY();
  if (dnsDomainIs(host, "api.radarr.video")) return PROXY();
  if (dnsDomainIs(host, "sonarr.tv")) return PROXY();
  if (dnsDomainIs(host, "lidarr.audio")) return PROXY();
  if (dnsDomainIs(host, "api.lidarr.audio")) return PROXY();
  if (dnsDomainIs(host, "jackett.dev")) return PROXY();
  if (url.indexOf("jackett") !== -1) return PROXY();
  if (dnsDomainIs(host, "flaresolverr")) return PROXY();
  if (dnsDomainIs(host, "tmdb.org")) return PROXY();
  if (dnsDomainIs(host, "themoviedb.org")) return PROXY();
  if (dnsDomainIs(host, "musicbrainz.org")) return PROXY();
  if (dnsDomainIs(host, "metabrainz.org")) return PROXY();
  if (dnsDomainIs(host, "coverartarchive.org")) return PROXY();
  if (dnsDomainIs(host, "fanart.tv")) return PROXY();
  if (dnsDomainIs(host, "theaudiodb.com")) return PROXY();
  if (dnsDomainIs(host, "last.fm")) return PROXY();
  if (dnsDomainIs(host, "discogs.com")) return PROXY();
  if (dnsDomainIs(host, "acoustid.org")) return PROXY();
  if (dnsDomainIs(host, "acousticbrainz.org")) return PROXY();
  if (dnsDomainIs(host, "brainz.org")) return PROXY();
  if (dnsDomainIs(host, "musicbrainzpicard.live")) return PROXY();
  return DIRECT_CONN();
}