function FindProxyForURL(url, host) {
  host = (host || "").toLowerCase();
  url = (url || "").toLowerCase();

  function PROXY_CONN() { return "PROXY 192.168.50.135:7897"; }
  function DIRECT_CONN() { return "DIRECT"; }

  // Apple / App Store / iCloud — always DIRECT
  if (host === "apple.com" || shExpMatch(host, "*.apple.com")) return DIRECT_CONN();
  if (host === "icloud.com" || shExpMatch(host, "*.icloud.com")) return DIRECT_CONN();
  if (host === "itunes.com" || shExpMatch(host, "*.itunes.com")) return DIRECT_CONN();
  if (host === "mzstatic.com" || shExpMatch(host, "*.mzstatic.com")) return DIRECT_CONN();
  if (host === "cdn-apple.com" || shExpMatch(host, "*.cdn-apple.com")) return DIRECT_CONN();
  if (host === "aaplimg.com" || shExpMatch(host, "*.aaplimg.com")) return DIRECT_CONN();
  if (host === "apple-dns.net" || shExpMatch(host, "*.apple-dns.net")) return DIRECT_CONN();
  if (host === "apple-cloudkit.com" || shExpMatch(host, "*.apple-cloudkit.com")) return DIRECT_CONN();
  if (host === "apps.apple.com" || shExpMatch(host, "*.apps.apple.com")) return DIRECT_CONN();
  if (host === "appstoreconnect.apple.com" || shExpMatch(host, "*.appstoreconnect.apple.com")) return DIRECT_CONN();
  if (host === "app-attest.apple.com" || shExpMatch(host, "*.app-attest.apple.com")) return DIRECT_CONN();
  if (host === "akadns.net" || shExpMatch(host, "*.akadns.net")) return DIRECT_CONN();

  if (isPlainHostName(host) ||
      shExpMatch(host, "*.local") ||
      shExpMatch(host, "*.lan")) {
    return DIRECT_CONN();
  }

  var resolved = dnsResolve(host);
  if (resolved) {
    if (isInNet(resolved, "127.0.0.0", "255.0.0.0") ||
        isInNet(resolved, "10.0.0.0", "255.0.0.0") ||
        isInNet(resolved, "172.16.0.0", "255.240.0.0") ||
        isInNet(resolved, "192.168.0.0", "255.255.0.0")) {
      return DIRECT_CONN();
    }
  }

  if (host === "localhost") return DIRECT_CONN();
  if (host === "youtube.com" || shExpMatch(host, "*.youtube.com")) return PROXY_CONN();
  if (host === "www.youtube.com" || shExpMatch(host, "*.www.youtube.com")) return PROXY_CONN();
  if (host === "m.youtube.com" || shExpMatch(host, "*.m.youtube.com")) return PROXY_CONN();
  if (host === "youtu.be" || shExpMatch(host, "*.youtu.be")) return PROXY_CONN();
  if (host === "youtube.googleapis.com" || shExpMatch(host, "*.youtube.googleapis.com")) return PROXY_CONN();
  if (host === "youtubei.googleapis.com" || shExpMatch(host, "*.youtubei.googleapis.com")) return PROXY_CONN();
  if (host === "youtubeembeddedplayer.googleapis.com" || shExpMatch(host, "*.youtubeembeddedplayer.googleapis.com")) return PROXY_CONN();
  if (host === "googlevideo.com" || shExpMatch(host, "*.googlevideo.com")) return PROXY_CONN();
  if (host === "ytimg.com" || shExpMatch(host, "*.ytimg.com")) return PROXY_CONN();
  if (host === "s.ytimg.com" || shExpMatch(host, "*.s.ytimg.com")) return PROXY_CONN();
  if (host === "i.ytimg.com" || shExpMatch(host, "*.i.ytimg.com")) return PROXY_CONN();
  if (host === "ggpht.com" || shExpMatch(host, "*.ggpht.com")) return PROXY_CONN();
  if (host === "googleusercontent.com" || shExpMatch(host, "*.googleusercontent.com")) return PROXY_CONN();
  if (host.indexOf("youtube") !== -1) return PROXY_CONN();
  if (host.indexOf("googlevideo") !== -1) return PROXY_CONN();
  if (host.indexOf("ytimg") !== -1) return PROXY_CONN();
  if (host.indexOf("ggpht") !== -1) return PROXY_CONN();
  if (host === "discord.com" || shExpMatch(host, "*.discord.com")) return PROXY_CONN();
  if (host === "discord.gg" || shExpMatch(host, "*.discord.gg")) return PROXY_CONN();
  if (host === "discordapp.com" || shExpMatch(host, "*.discordapp.com")) return PROXY_CONN();
  if (host === "discordapp.net" || shExpMatch(host, "*.discordapp.net")) return PROXY_CONN();
  if (host === "discordcdn.com" || shExpMatch(host, "*.discordcdn.com")) return PROXY_CONN();
  if (host === "cdn.discordapp.com" || shExpMatch(host, "*.cdn.discordapp.com")) return PROXY_CONN();
  if (host === "media.discordapp.net" || shExpMatch(host, "*.media.discordapp.net")) return PROXY_CONN();
  if (host === "images-ext-1.discordapp.net" || shExpMatch(host, "*.images-ext-1.discordapp.net")) return PROXY_CONN();
  if (host === "images-ext-2.discordapp.net" || shExpMatch(host, "*.images-ext-2.discordapp.net")) return PROXY_CONN();
  if (host === "status.discord.com" || shExpMatch(host, "*.status.discord.com")) return PROXY_CONN();
  if (host === "discord.media" || shExpMatch(host, "*.discord.media")) return PROXY_CONN();
  if (host === "gateway.discord.gg" || shExpMatch(host, "*.gateway.discord.gg")) return PROXY_CONN();
  if (host === "voice.discord.gg" || shExpMatch(host, "*.voice.discord.gg")) return PROXY_CONN();
  if (host === "clientconfig.discord.com" || shExpMatch(host, "*.clientconfig.discord.com")) return PROXY_CONN();
  if (host === "discord-attachments-uploads-prd.storage.googleapis.com" || shExpMatch(host, "*.discord-attachments-uploads-prd.storage.googleapis.com")) return PROXY_CONN();
  if (host.indexOf("rpc") !== -1) return PROXY_CONN();
  if (host.indexOf("discord-media") !== -1) return PROXY_CONN();
  if (host.indexOf("discord-gateway") !== -1) return PROXY_CONN();
  if (host.indexOf("discord") !== -1) return PROXY_CONN();
  if (host === "reddit.com") return PROXY_CONN();
  if (host === "www.reddit.com") return PROXY_CONN();
  if (host === "oauth.reddit.com") return PROXY_CONN();
  if (host === "gateway.reddit.com") return PROXY_CONN();
  if (host === "events.reddit.com") return PROXY_CONN();
  if (host === "redd.it" || shExpMatch(host, "*.redd.it")) return PROXY_CONN();
  if (host === "redditstatic.com" || shExpMatch(host, "*.redditstatic.com")) return PROXY_CONN();
  if (host === "redditmedia.com" || shExpMatch(host, "*.redditmedia.com")) return PROXY_CONN();
  if (host === "reddituploads.com" || shExpMatch(host, "*.reddituploads.com")) return PROXY_CONN();
  if (host === "i.redd.it") return PROXY_CONN();
  if (host === "preview.redd.it") return PROXY_CONN();
  if (host === "v.redd.it") return PROXY_CONN();
  if (host === "openai.com" || shExpMatch(host, "*.openai.com")) return PROXY_CONN();
  if (host === "chatgpt.com" || shExpMatch(host, "*.chatgpt.com")) return PROXY_CONN();
  if (host === "ai.com" || shExpMatch(host, "*.ai.com")) return PROXY_CONN();
  if (host === "auth0.openai.com" || shExpMatch(host, "*.auth0.openai.com")) return PROXY_CONN();
  if (host === "chat.openai.com" || shExpMatch(host, "*.chat.openai.com")) return PROXY_CONN();
  if (host === "cdn.openai.com" || shExpMatch(host, "*.cdn.openai.com")) return PROXY_CONN();
  if (host === "oaiusercontent.com" || shExpMatch(host, "*.oaiusercontent.com")) return PROXY_CONN();
  if (host === "openaicom.imgix.net" || shExpMatch(host, "*.openaicom.imgix.net")) return PROXY_CONN();
  if (host === "openaicom-api.akamaized.net" || shExpMatch(host, "*.openaicom-api.akamaized.net")) return PROXY_CONN();
  if (host === "play.google.com" || shExpMatch(host, "*.play.google.com")) return PROXY_CONN();
  if (host === "accounts.google.com" || shExpMatch(host, "*.accounts.google.com")) return PROXY_CONN();
  if (host === "googleapis.com" || shExpMatch(host, "*.googleapis.com")) return PROXY_CONN();
  if (host === "gstatic.com" || shExpMatch(host, "*.gstatic.com")) return PROXY_CONN();
  if (host === "apis.google.com" || shExpMatch(host, "*.apis.google.com")) return PROXY_CONN();
  if (host === "threads.com" || shExpMatch(host, "*.threads.com")) return PROXY_CONN();
  if (host === "threads.net" || shExpMatch(host, "*.threads.net")) return PROXY_CONN();
  if (host.indexOf("threads") !== -1) return PROXY_CONN();
  if (host === "instagram.com" || shExpMatch(host, "*.instagram.com")) return PROXY_CONN();
  if (host === "i.instagram.com" || shExpMatch(host, "*.i.instagram.com")) return PROXY_CONN();
  if (host === "api.instagram.com" || shExpMatch(host, "*.api.instagram.com")) return PROXY_CONN();
  if (host === "graph.instagram.com" || shExpMatch(host, "*.graph.instagram.com")) return PROXY_CONN();
  if (host === "b-graph.instagram.com" || shExpMatch(host, "*.b-graph.instagram.com")) return PROXY_CONN();
  if (host === "cdninstagram.com" || shExpMatch(host, "*.cdninstagram.com")) return PROXY_CONN();
  if (host === "static.cdninstagram.com" || shExpMatch(host, "*.static.cdninstagram.com")) return PROXY_CONN();
  if (host === "scontent.cdninstagram.com" || shExpMatch(host, "*.scontent.cdninstagram.com")) return PROXY_CONN();
  if (host === "igcdn.net" || shExpMatch(host, "*.igcdn.net")) return PROXY_CONN();
  if (host === "instagram.c10r.facebook.com" || shExpMatch(host, "*.instagram.c10r.facebook.com")) return PROXY_CONN();
  if (host === "facebook.com" || shExpMatch(host, "*.facebook.com")) return PROXY_CONN();
  if (host === "facebook.net" || shExpMatch(host, "*.facebook.net")) return PROXY_CONN();
  if (host === "fb.com" || shExpMatch(host, "*.fb.com")) return PROXY_CONN();
  if (host === "fbcdn.net" || shExpMatch(host, "*.fbcdn.net")) return PROXY_CONN();
  if (host === "xx.fbcdn.net" || shExpMatch(host, "*.xx.fbcdn.net")) return PROXY_CONN();
  if (host === "tfbnw.net" || shExpMatch(host, "*.tfbnw.net")) return PROXY_CONN();
  if (host === "connect.facebook.net" || shExpMatch(host, "*.connect.facebook.net")) return PROXY_CONN();
  if (host === "edge-chat.facebook.com" || shExpMatch(host, "*.edge-chat.facebook.com")) return PROXY_CONN();
  if (host === "edge-mqtt.facebook.com" || shExpMatch(host, "*.edge-mqtt.facebook.com")) return PROXY_CONN();
  if (host === "mqtt-mini.facebook.com" || shExpMatch(host, "*.mqtt-mini.facebook.com")) return PROXY_CONN();
  if (host === "star.c10r.facebook.com" || shExpMatch(host, "*.star.c10r.facebook.com")) return PROXY_CONN();
  if (host === "star-mini.c10r.facebook.com" || shExpMatch(host, "*.star-mini.c10r.facebook.com")) return PROXY_CONN();
  if (host === "graph.facebook.com" || shExpMatch(host, "*.graph.facebook.com")) return PROXY_CONN();
  if (host === "video.xx.fbcdn.net" || shExpMatch(host, "*.video.xx.fbcdn.net")) return PROXY_CONN();
  if (host === "scontent.xx.fbcdn.net" || shExpMatch(host, "*.scontent.xx.fbcdn.net")) return PROXY_CONN();
  if (host === "static.xx.fbcdn.net" || shExpMatch(host, "*.static.xx.fbcdn.net")) return PROXY_CONN();
  if (host === "whatsapp.com" || shExpMatch(host, "*.whatsapp.com")) return PROXY_CONN();
  if (host === "whatsapp.net" || shExpMatch(host, "*.whatsapp.net")) return PROXY_CONN();
  if (host.indexOf("instagram") !== -1) return PROXY_CONN();
  if (host.indexOf("fbcdn") !== -1) return PROXY_CONN();
  if (host.indexOf("facebook") !== -1) return PROXY_CONN();
  if (host.indexOf("scontent") !== -1) return PROXY_CONN();
  if (host.indexOf("metaverse") !== -1) return PROXY_CONN();
  if (host === "meta.com" || shExpMatch(host, "*.meta.com")) return PROXY_CONN();
  if (host === "graph.meta.com" || shExpMatch(host, "*.graph.meta.com")) return PROXY_CONN();
  if (host === "horizon.meta.com" || shExpMatch(host, "*.horizon.meta.com")) return PROXY_CONN();
  if (host === "horizon.oculus.com" || shExpMatch(host, "*.horizon.oculus.com")) return PROXY_CONN();
  if (host === "oculus.com" || shExpMatch(host, "*.oculus.com")) return PROXY_CONN();
  if (host === "oculuscdn.com" || shExpMatch(host, "*.oculuscdn.com")) return PROXY_CONN();
  if (host === "oculusvr.com" || shExpMatch(host, "*.oculusvr.com")) return PROXY_CONN();
  if (host === "graph.oculus.com" || shExpMatch(host, "*.graph.oculus.com")) return PROXY_CONN();
  if (host === "secure.oculus.com" || shExpMatch(host, "*.secure.oculus.com")) return PROXY_CONN();
  if (host === "edge.oculus.com" || shExpMatch(host, "*.edge.oculus.com")) return PROXY_CONN();
  if (host === "mqtt.meta.com" || shExpMatch(host, "*.mqtt.meta.com")) return PROXY_CONN();
  if (host === "mqtt-mini.meta.com" || shExpMatch(host, "*.mqtt-mini.meta.com")) return PROXY_CONN();
  if (host === "edge-mqtt.meta.com" || shExpMatch(host, "*.edge-mqtt.meta.com")) return PROXY_CONN();
  if (host.indexOf("oculus") !== -1) return PROXY_CONN();
  if (host.indexOf("quest") !== -1) return PROXY_CONN();
  if (host.indexOf("horizon") !== -1) return PROXY_CONN();
  if (host === "notion.so" || shExpMatch(host, "*.notion.so")) return PROXY_CONN();
  if (host === "notion.site" || shExpMatch(host, "*.notion.site")) return PROXY_CONN();
  if (host === "notion-static.com" || shExpMatch(host, "*.notion-static.com")) return PROXY_CONN();
  if (host === "proton.me" || shExpMatch(host, "*.proton.me")) return PROXY_CONN();
  if (host === "protonmail.com" || shExpMatch(host, "*.protonmail.com")) return PROXY_CONN();
  if (host === "protonvpn.com" || shExpMatch(host, "*.protonvpn.com")) return PROXY_CONN();
  if (host.indexOf("proton") !== -1) return PROXY_CONN();
  if (host === "api.telegram.org") return PROXY_CONN();
  if (host === "t.me" || shExpMatch(host, "*.t.me")) return PROXY_CONN();
  if (host === "telegram.org" || shExpMatch(host, "*.telegram.org")) return PROXY_CONN();
  if (host === "telegram.me" || shExpMatch(host, "*.telegram.me")) return PROXY_CONN();
  if (host === "telegram.dog" || shExpMatch(host, "*.telegram.dog")) return PROXY_CONN();
  if (host === "telesco.pe" || shExpMatch(host, "*.telesco.pe")) return PROXY_CONN();
  if (host === "cdn-telegram.org" || shExpMatch(host, "*.cdn-telegram.org")) return PROXY_CONN();
  if (host === "telegram-cdn.org" || shExpMatch(host, "*.telegram-cdn.org")) return PROXY_CONN();
  if (host === "telegra.ph" || shExpMatch(host, "*.telegra.ph")) return PROXY_CONN();
  if (host === "graph.org" || shExpMatch(host, "*.graph.org")) return PROXY_CONN();
  if (host === "garlandtools.org" || shExpMatch(host, "*.garlandtools.org")) return PROXY_CONN();
  if (host === "universalis.app" || shExpMatch(host, "*.universalis.app")) return PROXY_CONN();
  if (host === "xivgear.app" || shExpMatch(host, "*.xivgear.app")) return PROXY_CONN();
  if (host === "raidplan.io" || shExpMatch(host, "*.raidplan.io")) return PROXY_CONN();
  if (host === "finalfantasyxiv.com" || shExpMatch(host, "*.finalfantasyxiv.com")) return PROXY_CONN();
  if (host === "ffxiv.com" || shExpMatch(host, "*.ffxiv.com")) return PROXY_CONN();
  if (host === "square-enix.com" || shExpMatch(host, "*.square-enix.com")) return PROXY_CONN();
  if (host === "sqexcdn.com" || shExpMatch(host, "*.sqexcdn.com")) return PROXY_CONN();
  if (host === "ffxivteamcraft.com" || shExpMatch(host, "*.ffxivteamcraft.com")) return PROXY_CONN();
  if (host === "fflogs.com" || shExpMatch(host, "*.fflogs.com")) return PROXY_CONN();
  if (host === "xivanalysis.com" || shExpMatch(host, "*.xivanalysis.com")) return PROXY_CONN();
  if (host === "consolegameswiki.com" || shExpMatch(host, "*.consolegameswiki.com")) return PROXY_CONN();
  if (host === "ffxiv.consolegameswiki.com" || shExpMatch(host, "*.ffxiv.consolegameswiki.com")) return PROXY_CONN();
  if (host.indexOf("lifehacker") !== -1) return PROXY_CONN();
  if (host === "desec.io" || shExpMatch(host, "*.desec.io")) return PROXY_CONN();
  if (host === "patreon.com" || shExpMatch(host, "*.patreon.com")) return PROXY_CONN();
  if (host.indexOf("patreon") !== -1) return PROXY_CONN();
  if (host === "canva.com" || shExpMatch(host, "*.canva.com")) return PROXY_CONN();
  if (host === "canva.dev" || shExpMatch(host, "*.canva.dev")) return PROXY_CONN();
  if (host === "canvausercontent.com" || shExpMatch(host, "*.canvausercontent.com")) return PROXY_CONN();
  if (host === "cdn.canva.com" || shExpMatch(host, "*.cdn.canva.com")) return PROXY_CONN();
  if (host === "static.canva.com" || shExpMatch(host, "*.static.canva.com")) return PROXY_CONN();
  if (host === "curseforge.com" || shExpMatch(host, "*.curseforge.com")) return PROXY_CONN();
  if (host === "ipleak.net" || shExpMatch(host, "*.ipleak.net")) return PROXY_CONN();
  if (host === "4kwallpapers.com" || shExpMatch(host, "*.4kwallpapers.com")) return PROXY_CONN();
  if (host === "unraid.net" || shExpMatch(host, "*.unraid.net")) return PROXY_CONN();
  if (host === "craft.cloud" || shExpMatch(host, "*.craft.cloud")) return PROXY_CONN();
  if (host === "cdn.craft.cloud" || shExpMatch(host, "*.cdn.craft.cloud")) return PROXY_CONN();
  if (host === "beehiiv.com" || shExpMatch(host, "*.beehiiv.com")) return PROXY_CONN();
  if (host === "googletagmanager.com" || shExpMatch(host, "*.googletagmanager.com")) return PROXY_CONN();
  if (host === "doubleclick.net" || shExpMatch(host, "*.doubleclick.net")) return PROXY_CONN();
  if (host === "googleadservices.com" || shExpMatch(host, "*.googleadservices.com")) return PROXY_CONN();
  if (host === "itch.io" || shExpMatch(host, "*.itch.io")) return PROXY_CONN();
  if (host === "html-classic.itch.zone") return PROXY_CONN();
  if (host === "itch.zone" || shExpMatch(host, "*.itch.zone")) return PROXY_CONN();
  if (host.indexOf("hentaihaven") !== -1) return PROXY_CONN();
  if (host.indexOf("hentai") !== -1) return PROXY_CONN();
  if (host.indexOf("pornhub") !== -1) return PROXY_CONN();
  if (host.indexOf("phncdn") !== -1) return PROXY_CONN();
  if (host.indexOf("pornolab") !== -1) return PROXY_CONN();
  if (host.indexOf("eporner") !== -1) return PROXY_CONN();
  if (host.indexOf("celebjihad") !== -1) return PROXY_CONN();
  if (host.indexOf("xvideos") !== -1) return PROXY_CONN();
  if (host.indexOf("xnxx") !== -1) return PROXY_CONN();
  if (host.indexOf("youporn") !== -1) return PROXY_CONN();
  if (host.indexOf("redtube") !== -1) return PROXY_CONN();
  if (host === "hanime.tv" || shExpMatch(host, "*.hanime.tv")) return PROXY_CONN();
  if (host === "hanime-cdn.com" || shExpMatch(host, "*.hanime-cdn.com")) return PROXY_CONN();
  if (host === "highwinds-cdn.com" || shExpMatch(host, "*.highwinds-cdn.com")) return PROXY_CONN();
  if (host.indexOf("hydaelyn") !== -1) return PROXY_CONN();
  if (host === "omni-player.hanime.tv") return PROXY_CONN();
  if (host === "hhcdn.net" || shExpMatch(host, "*.hhcdn.net")) return PROXY_CONN();
  if (host === "hentaicdn.com" || shExpMatch(host, "*.hentaicdn.com")) return PROXY_CONN();
  if (host === "hanime1.me" || shExpMatch(host, "*.hanime1.me")) return PROXY_CONN();
  if (host === "dirtyship.com" || shExpMatch(host, "*.dirtyship.com")) return PROXY_CONN();
  if (host === "ds-cdn.com" || shExpMatch(host, "*.ds-cdn.com")) return PROXY_CONN();
  if (host === "ds1cdn.com" || shExpMatch(host, "*.ds1cdn.com")) return PROXY_CONN();
  if (host === "cloudflarestream.com" || shExpMatch(host, "*.cloudflarestream.com")) return PROXY_CONN();
  if (host === "fastpic.org" || shExpMatch(host, "*.fastpic.org")) return PROXY_CONN();
  if (host.indexOf("rutracker") !== -1) return PROXY_CONN();
  if (host.indexOf("rutor") !== -1) return PROXY_CONN();
  if (host.indexOf("tfile") !== -1) return PROXY_CONN();
  if (host.indexOf("nnmclub") !== -1) return PROXY_CONN();
  if (host.indexOf("torrent") !== -1) return PROXY_CONN();
  if (host.indexOf("1337x") !== -1) return PROXY_CONN();
  if (host.indexOf("torlock") !== -1) return PROXY_CONN();
  if (host.indexOf("rarbg") !== -1) return PROXY_CONN();
  if (host.indexOf("torrentgalaxy") !== -1) return PROXY_CONN();
  if (host.indexOf("limetorrents") !== -1) return PROXY_CONN();
  if (host.indexOf("piratebay") !== -1) return PROXY_CONN();
  if (host.indexOf("seedpeer") !== -1) return PROXY_CONN();
  if (host.indexOf("bitsearch") !== -1) return PROXY_CONN();
  if (host.indexOf("magnetdl") !== -1) return PROXY_CONN();
  if (host.indexOf("torrends") !== -1) return PROXY_CONN();
  if (host.indexOf("glotorrents") !== -1) return PROXY_CONN();
  if (host.indexOf("ettv") !== -1) return PROXY_CONN();
  if (host.indexOf("yts") !== -1) return PROXY_CONN();
  if (host.indexOf("nyaa") !== -1) return PROXY_CONN();
  if (host.indexOf("animetosho") !== -1) return PROXY_CONN();
  if (host === "servarr.com" || shExpMatch(host, "*.servarr.com")) return PROXY_CONN();
  if (host === "radarr.video" || shExpMatch(host, "*.radarr.video")) return PROXY_CONN();
  if (host === "api.radarr.video" || shExpMatch(host, "*.api.radarr.video")) return PROXY_CONN();
  if (host === "sonarr.tv" || shExpMatch(host, "*.sonarr.tv")) return PROXY_CONN();
  if (host === "lidarr.audio" || shExpMatch(host, "*.lidarr.audio")) return PROXY_CONN();
  if (host === "api.lidarr.audio" || shExpMatch(host, "*.api.lidarr.audio")) return PROXY_CONN();
  if (host === "jackett.dev" || shExpMatch(host, "*.jackett.dev")) return PROXY_CONN();
  if (host.indexOf("jackett") !== -1) return PROXY_CONN();
  if (host === "flaresolverr" || shExpMatch(host, "*.flaresolverr")) return PROXY_CONN();
  if (host === "tmdb.org" || shExpMatch(host, "*.tmdb.org")) return PROXY_CONN();
  if (host === "themoviedb.org" || shExpMatch(host, "*.themoviedb.org")) return PROXY_CONN();
  if (host === "opensubtitles.com" || shExpMatch(host, "*.opensubtitles.com")) return PROXY_CONN();
  if (host === "www.opensubtitles.com" || shExpMatch(host, "*.www.opensubtitles.com")) return PROXY_CONN();
  if (host === "api.opensubtitles.com" || shExpMatch(host, "*.api.opensubtitles.com")) return PROXY_CONN();
  if (host === "opensubtitles.org" || shExpMatch(host, "*.opensubtitles.org")) return PROXY_CONN();
  if (host === "opensubtitles.vip" || shExpMatch(host, "*.opensubtitles.vip")) return PROXY_CONN();
  if (host === "podnapisi.net" || shExpMatch(host, "*.podnapisi.net")) return PROXY_CONN();
  if (host === "www.podnapisi.net" || shExpMatch(host, "*.www.podnapisi.net")) return PROXY_CONN();
  if (host === "yifysubtitles.ch" || shExpMatch(host, "*.yifysubtitles.ch")) return PROXY_CONN();
  if (host === "yifysubtitles.org" || shExpMatch(host, "*.yifysubtitles.org")) return PROXY_CONN();
  if (host === "yts.mx" || shExpMatch(host, "*.yts.mx")) return PROXY_CONN();
  if (host === "subscene.com" || shExpMatch(host, "*.subscene.com")) return PROXY_CONN();
  if (host === "addic7ed.com" || shExpMatch(host, "*.addic7ed.com")) return PROXY_CONN();
  if (host === "musicbrainz.org" || shExpMatch(host, "*.musicbrainz.org")) return PROXY_CONN();
  if (host === "metabrainz.org" || shExpMatch(host, "*.metabrainz.org")) return PROXY_CONN();
  if (host === "coverartarchive.org" || shExpMatch(host, "*.coverartarchive.org")) return PROXY_CONN();
  if (host === "fanart.tv" || shExpMatch(host, "*.fanart.tv")) return PROXY_CONN();
  if (host === "theaudiodb.com" || shExpMatch(host, "*.theaudiodb.com")) return PROXY_CONN();
  if (host === "last.fm" || shExpMatch(host, "*.last.fm")) return PROXY_CONN();
  if (host === "discogs.com" || shExpMatch(host, "*.discogs.com")) return PROXY_CONN();
  if (host === "acoustid.org" || shExpMatch(host, "*.acoustid.org")) return PROXY_CONN();
  if (host === "acousticbrainz.org" || shExpMatch(host, "*.acousticbrainz.org")) return PROXY_CONN();
  if (host === "brainz.org" || shExpMatch(host, "*.brainz.org")) return PROXY_CONN();
  if (host === "musicbrainzpicard.live" || shExpMatch(host, "*.musicbrainzpicard.live")) return PROXY_CONN();
  return DIRECT_CONN();
}
